language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - rbx
matrix:
  include:
    - rvm: ruby-2.2.5
      os: osx
      osx_image: xcode7.3
    - rvm: ruby-2.2.5
      os: osx
      osx_image: xcode6.4
    - rvm: ruby-2.2.2
      os: osx
      osx_image: beta-xcode6.2
    - rvm: system
      os: osx
      osx_image: xcode7.3
    - rvm: ruby-2.3.1-clang
      env: CXX=clang++
    - rvm: 1.9.3
  allow_failures:
    - rvm: 1.9.3
  fast_finish: true
dist: trusty
addons:
  apt:
    packages:
      - clang
bundler_args: --jobs=4 --retry=3
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo gem install bundler; fi
script:
  - if ! [ "$(ls -A vendor/v8/.git)" ] ; then rm -rf vendor/v8; fi
  - MAKEFLAGS+=-j8 bundle exec rake spec binary --trace
deploy:
  provider: releases
  file: $(git ls-files -o pkg | head -1)
  api_key:
    secure: OMCBceg89uRnU+FIPAPbeOK2pISvV4Cz62r9iTRIGXQCOOXX8M40i77/3DmtkMtc9FEuNyAu1+CH886PL2WtZZPK4CmEU3HuqXz1a5VsCI+zcAZL1tevKvblXOVQ3MG+B/SZRC3rEzGwjk4027WtzCCGoGCLUu4TFJP05+/8XN4=
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
cache:
  bundler: true
  directories:
    - vendor/v8/.git
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
