rvm:
  - 2.0.0
  - 1.9.2
  - 1.9.3
  - rbx-19mode
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
before_install:
  - sudo apt-get update
  - sudo apt-get install git-svn